theme: jekyll-theme-slate
title: Devendra's Log
google_analytics: UA-114405074-1
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  