title: Devendra's Log
description: Devendra's Log
google_analytics: UA-114405074-1
theme: jekyll-theme-slate
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
repository: tewarid/tewarid.github.io

