theme: jekyll-theme-slate
title: Dev's Log
description: make ~ learn ~ share ~ care
google_analytics: UA-114405074-1
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  