title: Devendra's Mog
description: Devendra's Mutable Log (Mog)
google_analytics: UA-114405074-1
theme: jekyll-theme-slate
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
repository: tewarid/tewarid.github.io

